#
#   Setup
title: Fight The Bunnies

#
#   Build
baseurl: ""
source: "./app"
permalink: none
#permalink: /:categories/:title/
#permalink: /:categories/:year/:month/:day/:title.html

#
#   Includes
include:

#
#   Excludes
exclude:
  - node_modules
  - gulpfile.js
  - package.json

#
#   Collections
collections:
  pages:
    output: true
    permalink: /:title

defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
#    - scope:
#        type: projects
#      values:
#        layout: project
#    - scope:
#        type: tools
#      values:
#        layout: tool
#
