#
#   Setup
title: Fight The Bunnies

#
#   Build
baseurl: "/fightthebunnies"     # remote
#baseurl: ""                     # local
url: ""                         # the base hostname & protocol for your site
#source: "./"
permalink: /:categories/:year/:month/:title.html

#
#   Includes
include:

#
#   Excludes
exclude:
  - node_modules
  - gulpfile.js
  - package.json

#
#   Collections
collections:
  pages:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /:collection/:name.html

defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: projects
    values:
      layout: project
