#
#   Setup
title: Fight The Bunnies

#
#   Build
baseurl: ""
source: "./app"
permalink: none
#permalink: /:categories/:title/
#permalink: /:categories/:year/:month/:day/:title.html

#
#   Includes
include:

#
#   Excludes
exclude:
  - node_modules
  - gulpfile.js
  - package.json

##
##   Collections
#collections:
#    projects:
#        output: true
#    tools:
#        output: true
#
#defaults:
#    - scope:
#        type: projects
#      values:
#        layout: project
#    - scope:
#        type: tools
#      values:
#        layout: tool
#
